# Created by: archinstall
# Created on: 2026-05-28_18-42-11
title	Arch Linux (linux)
linux	/vmlinuz-linux
initrd	/initramfs-linux.img
#options root=PARTUUID=086625ca-390c-494e-bbb4-e5a8b0d53e3d zswap.enabled=0 rootflags=subvol=@ rw rootfstype=btrfs
options root=PARTUUID=086625ca-390c-494e-bbb4-e5a8b0d53e3d zswap.enabled=0 rootflags=subvol=@ rw rootfstype=btrfs quite splash loglevel=3 systemd.show_status=error rd.udev.log_level=3 vt.global_cursor_default=0 nvidia_drm.modeset=1
